<?php
/**
 * @package     ABC
 * @subpackage  Template File
 *
 * @copyright   Copyright (C) 2005 - 2013 Joomlashack. Meritage Assets.
 *              All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');

?>
<doctype>
<html>
    <head>
        <w:head />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Quicksand">
    </head>
    <body<?php if ($bodyclass != "") :?> class="<?php echo $bodyclass?>"<?php endif; ?>>

        <?php if ($this->countModules('toolbar')) : ?>
        <!-- toolbar -->
        <w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode;?>" wrapClass="navbar-fixed-top" type="toolbar" name="toolbar" />
        <?php endif; ?>

        <?php if ($this->countModules('menu')) : ?>
        <!-- menu -->
        <div class="menu-background z3">
            <w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode;?>"  name="menu" />
        </div>
        <?php endif; ?>

        <header id="header">
            <div class="<?php echo $containerClass ?>">
                <div class="<?php echo $gridMode; ?> clearfix">
                    <div class="span1"></div>
                    <div class="span10">
                        <div class="row-fluid">
                            <w:logo class="clearfix" name="top" />
                        </div>
                    </div>
                    <div class="span1"></div>
                </div>
            </div>
        </header>

        <?php if ($this->countModules('featured')) : ?>
        <div class="wrapper-container-featured">
            <div class="featured-background"></div>
            <div id="featured" class="<?php echo $containerClass ?> top-space ">
                <w:module type="row-fluid" name="featured" chrome="wrightflexgrid" />
           </div>
        </div>
        <?php endif; ?>

        <div class="<?php echo $containerClass ?> container-border absolute absolute-top">
        </div>
        <div class="<?php echo $containerClass ?> top-space">
            <?php if ($this->countModules('grid-top')) : ?>
            <div id="grid-top">
                <div class="border-wrapp">
                    <div class="border-wrapp-relative">
                        <div class="border-gridtop"></div>
                    </div>
                </div>
                <div class="grid-top">
                    <w:module type="row-fluid" name="grid-top" chrome="wrightflexgrid" />
                </div>
            </div>
            <?php endif; ?>

            <?php if ($this->countModules('grid-top2')) : ?>
            <!-- grid-top2 -->
            <div id="grid-top2">
                <w:module type="row-fluid" name="grid-top2" chrome="wrightflexgrid" />
            </div>
            <?php endif; ?>

            <div class="content-wrapp">
                <div id="main-content" class="row-fluid">
                    <!-- sidebar1 -->
                    <aside id="sidebar1">
                        <w:module name="sidebar1" chrome="xhtml" />
                    </aside>
                    <!-- main -->
                    <section id="main">
                        <?php if ($this->countModules('above-content')) : ?>
                        <!-- above-content -->
                        <div id="above-content">
                            <w:module type="none" name="above-content" chrome="xhtml" />
                        </div>
                        <?php endif; ?>
                        <?php if ($this->countModules('breadcrumbs')) : ?>
                        <!-- breadcrumbs -->
                        <div id="breadcrumbs">
                            <w:module type="single" name="breadcrumbs" chrome="none" />
                        </div>
                        <?php endif; ?>
                        <!-- component -->
                        <w:content />
                        <?php if ($this->countModules('below-content')) : ?>
                        <!-- below-content -->
                        <div id="below-content">
                            <w:module type="none" name="below-content" chrome="xhtml" />
                        </div>
                        <?php endif; ?>
                    </section>
                    <!-- sidebar2 -->
                    <aside id="sidebar2">
                        <w:module name="sidebar2" chrome="xhtml" />
                    </aside>
                </div>
            </div>
            <?php if ($this->countModules('grid-bottom')) : ?>
            <div id="grid-bottom" >
                <w:module type="row-fluid" name="grid-bottom" chrome="wrightflexgrid" />
            </div>
            <?php endif; ?>
            <?php if ($this->countModules('grid-bottom2')) : ?>
            <div id="grid-bottom2" >
                <w:module type="row-fluid" name="grid-bottom2" chrome="wrightflexgrid" />
            </div>
            <?php endif; ?>

        </div>

        <!-- footer -->

        <div class="wrapper-footer z3">
            <footer id="footer" <?php if ($this->params->get('stickyFooter',1)) : ?> class="sticky"<?php endif;?>>
                <?php if ($this->countModules('bottom-menu')) : ?>
                <!-- bottom-menu -->
                <w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode;?>" name="bottom-menu" />
                <?php endif; ?>
                <div class="<?php echo $containerClass ?>">
                    <div class="border-closure-ft">
                        <div class="footer-content">
                            <?php if ($this->countModules('footer')) : ?>
                             <w:module type="none" name="footer" chrome="xhtml" />
                            <?php endif; ?>
                            <w:footer />
                        </div>
                    </div>
                 </div>
            </footer>
        </div>

        <?php
            $browser = JBrowser::getInstance();

            if ($browser->getBrowser() == 'msie')
            {
                $major = $browser->getMajor();

                if ((int)$major <= 9) {
                    echo "<script type='text/javascript' src='" . JURI::root() .  "templates/" . $this->document->template . "/js/fallback.js'></script>";
                }

            }
        ?>
    </body>
</html>
